patients: patients.tsv
db: "sqlite:////home/jingyu/git/cnv/output/svrare.sqlite"
gene_tbx: "data/Homo_sapiens.GRCh37.75.sorted.gtf.gz"
params:
  output_format: tsv
  distance: 0.5
  cutoffs:
    internal_freq: 0.1
    gnomad_freq: 0.01
    dbvar_count: 73
    decipher_freq: 0.01
dbvar:
  LOSS: "data/dbVAR_SV/GRCh37.nr_deletions.tsv.gz"
  GAIN: "data/GRCh37.nr_duplications.tsv.gz"
decipher: "data/population_cnv_grch37.sorted.txt.gz"
gnomad: "data/gnomad_v2.1_sv.sites.converted.vcf.gz"

# hpo source
hpo_obo_url: http://purl.obolibrary.org/obo/hp.obo
hpo_gene_url: http://purl.obolibrary.org/obo/hp/hpoa/phenotype_to_genes.txt

# gnomad gene constraint
gnomad_constraint_url: "https://storage.googleapis.com/gcp-public-data--gnomad/release/2.1.1/constraint/gnomad.v2.1.1.lof_metrics.by_gene.txt.bgz"
